import { createGameContext, safeDelta, smoothToward } from '../../js/render-utils.js?v=3.0.0';

const WIDTH=320,HEIGHT=240,WORLD=1520;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const STAGES=[
  {name:'STEEL OUTSKIRTS',sky:['#486779','#b6cbd4'],accent:'#83cbe8'},
  {name:'SILVER HEIGHTS',sky:['#4f5367','#c9cbd4'],accent:'#d1b9ed'},
  {name:'ONYX CITADEL',sky:['#090b12','#414656'],accent:'#b0dfff'}
];

export default{
  id:'pixel-quest',title:'Pixel Quest',version:'1.0.0',
  create(){
    let root,canvas,ctx,services,frame=0,previousTime=0,state='title';
    let stageIndex=0,stage,player,cameraX=0,platforms=[],coins=[],enemies=[],particles=[];
    let score=0,high=0,bestStage=1,lives=3,checkpoint=40,held={left:false,right:false},attackTimer=0;
    const markup=()=>`<div class="quest-game"><canvas width="640" height="480" aria-label="Pixel Quest world"></canvas><div class="quest-hud"><span>WORLD <b id="quest-stage">1-1</b></span><span>COIN <b id="quest-coins">000</b></span><span>LIFE <b id="quest-life">3</b></span><span>HI <b id="quest-hi">000000</b></span></div><div class="quest-banner" id="quest-banner"></div><div class="quest-overlay" id="quest-overlay"><strong>PIXEL QUEST</strong><small>THREE WORLDS - HIDDEN CORES<br>RUN - JUMP - DEFEAT THE CITADEL</small><button data-quest="start">BEGIN QUEST</button><em>LEFT / RIGHT MOVE - A JUMP - B ATTACK</em></div><div class="quest-pause" id="quest-pause" hidden>PAUSED</div><button class="quest-exit" data-quest="exit" aria-label="Exit game">X</button></div>`;
    function makeStage(index){
      stage=STAGES[index];platforms=[];coins=[];enemies=[];const groundY=211;
      const gaps=index===0?[[300,350],[690,750],[1110,1170]]:index===1?[[240,310],[540,620],[865,950],[1220,1290]]:[[210,285],[470,545],[760,835],[1070,1140]];
      let cursor=0;gaps.forEach(([a,b])=>{platforms.push({x:cursor,y:groundY,w:a-cursor,h:35,ground:true});cursor=b;});platforms.push({x:cursor,y:groundY,w:WORLD-cursor,h:35,ground:true});
      for(let i=0;i<12;i++){const x=105+i*108+(i%3)*13,y=165-(i%3)*31;platforms.push({x,y,w:58+(i%2)*22,h:11});coins.push({x:x+18,y:y-13,taken:false},{x:x+39,y:y-13,taken:false});if(i%2===1)enemies.push({x:x+25,y:y-13,vx:(i%4<2?1:-1)*(31+index*7),min:x,max:x+58,hp:1+Math.floor(index/2),boss:false,hit:0});}
      for(let x=70;x<WORLD-80;x+=78){const overGap=gaps.some(([a,b])=>x>a&&x<b);if(!overGap)coins.push({x,y:190,taken:false});}
      [430,900].forEach((x,i)=>enemies.push({x,y:197,vx:(i? -1:1)*(36+index*8),min:x-70,max:x+100,hp:1,boss:false,hit:0}));
      if(index===2)enemies.push({x:1390,y:188,vx:-24,min:1290,max:1460,hp:12,boss:true,hit:0});
      checkpoint=40;player={x:40,y:180,vx:0,vy:0,w:13,h:19,grounded:false,face:1,invuln:0};cameraX=0;
    }
    function reset(){stageIndex=0;score=0;lives=3;makeStage(0);}
    function updateHud(){if(!root)return;root.querySelector('#quest-stage').textContent=`1-${stageIndex+1}`;root.querySelector('#quest-coins').textContent=String(Math.floor(score/10)).padStart(3,'0');root.querySelector('#quest-life').textContent=lives;root.querySelector('#quest-hi').textContent=String(high).padStart(6,'0');}
    function show(title,copy,button){const o=root.querySelector('#quest-overlay');o.hidden=false;o.innerHTML=`<strong>${title}</strong><small>${copy}</small><button data-quest="start">${button}</button><em>LEFT / RIGHT MOVE - A JUMP - B ATTACK</em>`;}
    function renderUi(){root.querySelector('#quest-pause').hidden=state!=='pause';if(state==='title')show('PIXEL QUEST',`BEST WORLD 1-${bestStage}<br>THREE WORLDS - ONE CITADEL`,'BEGIN QUEST');else if(state==='over')show('QUEST FAILED',`SCORE ${score}<br>CHECKPOINT LOST`,'TRY AGAIN');else if(state==='win')show('CITADEL CLEARED',`SCORE ${score}<br>THE KSR CORE IS RESTORED`,'PLAY AGAIN');else root.querySelector('#quest-overlay').hidden=true;updateHud();}
    function start(){reset();state='play';services.tone(440,.07,'square');renderUi();announce(stage.name);}
    function announce(text){const b=root.querySelector('#quest-banner');b.textContent=text;b.classList.add('show');setTimeout(()=>b.classList.remove('show'),1100);}
    function jump(){if(state==='play'&&player.grounded){player.vy=-215;player.grounded=false;services.tone(510,.04,'square');}}
    function attack(){if(state!=='play'||attackTimer>0)return;attackTimer=.22;services.tone(225,.035,'sawtooth');enemies.forEach(enemy=>{if(enemy.hp>0&&Math.abs(enemy.x-player.x)<(enemy.boss?38:28)&&Math.abs(enemy.y-player.y)<27&&Math.sign(enemy.x-player.x)===player.face){enemy.hp-=1;enemy.hit=.12;enemy.vx+=player.face*28;if(enemy.hp<=0){score+=enemy.boss?2500:150;burst(enemy.x,enemy.y,enemy.boss?'#fff':stage.accent,enemy.boss?24:8);}}});}
    function burst(x,y,color,count){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*90,vy:-20-Math.random()*70,life:.5,color});}
    function respawn(){lives-=1;services.tone(95,.18,'sawtooth');if(lives<=0){state='over';renderUi();return;}player.x=checkpoint;player.y=160;player.vx=player.vy=0;player.invuln=1.3;}
    function finishStage(){if(stageIndex===STAGES.length-1){state='win';score+=3000;high=Math.max(high,score);services.storage.set('pixelQuest:highScore',high);bestStage=3;services.storage.set('pixelQuest:bestStage',bestStage);services.tone(920,.16,'triangle');renderUi();return;}stageIndex+=1;bestStage=Math.max(bestStage,stageIndex+1);services.storage.set('pixelQuest:bestStage',bestStage);score+=800;makeStage(stageIndex);announce(STAGES[stageIndex].name);services.tone(780,.12,'triangle');updateHud();}
    function collidePlatforms(previousY){player.grounded=false;platforms.forEach(p=>{if(player.x+player.w/2<p.x||player.x-player.w/2>p.x+p.w)return;const bottom=player.y+player.h/2,previousBottom=previousY+player.h/2;if(player.vy>=0&&previousBottom<=p.y&&bottom>=p.y){player.y=p.y-player.h/2;player.vy=0;player.grounded=true;}});}
    function update(dt){particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=130*dt;p.life-=dt;});particles=particles.filter(p=>p.life>0);if(state!=='play')return;attackTimer=Math.max(0,attackTimer-dt);player.invuln=Math.max(0,player.invuln-dt);const move=(held.right?1:0)-(held.left?1:0);if(move)player.face=move;player.vx=smoothToward(player.vx,move*94,15,dt);const previousY=player.y;player.vy+=480*dt;player.x=clamp(player.x+player.vx*dt,4,WORLD-4);player.y+=player.vy*dt;collidePlatforms(previousY);if(player.y>260)respawn();if(player.x>720&&checkpoint<700){checkpoint=735;announce('CHECKPOINT');services.tone(690,.06,'triangle');}coins.forEach(coin=>{if(!coin.taken&&Math.hypot(coin.x-player.x,coin.y-player.y)<15){coin.taken=true;score+=10;services.tone(700,.025,'triangle');}});enemies.forEach(enemy=>{if(enemy.hp<=0)return;enemy.hit=Math.max(0,enemy.hit-dt);enemy.x+=enemy.vx*dt;if(enemy.x<enemy.min||enemy.x>enemy.max)enemy.vx*=-1;const dx=player.x-enemy.x;if(enemy.boss&&Math.abs(dx)<190)enemy.vx=smoothToward(enemy.vx,Math.sign(dx)*46,3,dt);if(Math.abs(dx)<(enemy.boss?21:15)&&Math.abs(player.y-enemy.y)<22&&player.invuln<=0){player.invuln=.8;player.vx=-Math.sign(dx)*120;player.vy=-120;respawn();}});enemies=enemies.filter(enemy=>enemy.hp>0);if(player.x>WORLD-45&&(!enemies.some(enemy=>enemy.boss)||stageIndex<2))finishStage();cameraX=smoothToward(cameraX,clamp(player.x-130,0,WORLD-WIDTH),7,dt);high=Math.max(high,score);updateHud();}
    function draw(){const sky=ctx.createLinearGradient(0,0,0,210);sky.addColorStop(0,stage.sky[0]);sky.addColorStop(1,stage.sky[1]);ctx.fillStyle=sky;ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#ffffff1a';for(let i=0;i<12;i++){const x=((i*83-cameraX*.18)%390)-35,y=45+(i%4)*19;ctx.beginPath();ctx.arc(x,y,10+(i%3)*6,0,Math.PI*2);ctx.fill();}ctx.fillStyle='#11182044';for(let i=0;i<18;i++){const x=i*91-cameraX*.38;ctx.fillRect(x,126-(i%4)*13,58,85);}ctx.save();ctx.translate(-cameraX,0);platforms.forEach(p=>{ctx.fillStyle=p.ground?'#171d22':'#29343c';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle=p.ground?'#9ba8b1':stage.accent;ctx.fillRect(p.x,p.y,p.w,3);});coins.forEach(c=>{if(c.taken)return;ctx.strokeStyle='#f4f6f7';ctx.lineWidth=2;ctx.beginPath();ctx.arc(c.x,c.y,4,0,Math.PI*2);ctx.stroke();});enemies.forEach(e=>{ctx.fillStyle=e.hit?'#fff':e.boss?'#23202c':'#4e606b';ctx.beginPath();ctx.roundRect(e.x-(e.boss?15:7),e.y-(e.boss?16:8),e.boss?30:14,e.boss?29:15,4);ctx.fill();ctx.fillStyle=stage.accent;ctx.fillRect(e.x-3,e.y-4,6,3);if(e.boss){ctx.fillStyle='#080a0c';ctx.fillRect(e.x-14,e.y-23,28,3);ctx.fillStyle='#fff';ctx.fillRect(e.x-14,e.y-23,28*e.hp/12,3);}});particles.forEach(p=>{ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,2,2);});ctx.globalAlpha=1;ctx.save();ctx.translate(player.x,player.y);ctx.scale(player.face,1);ctx.fillStyle=player.invuln>0&&Math.floor(performance.now()/70)%2?'#75808a':'#f5f7f8';ctx.beginPath();ctx.roundRect(-6,-10,12,18,3);ctx.fill();ctx.fillStyle='#11161a';ctx.fillRect(0,-5,4,3);ctx.fillRect(-7,8,5,3);ctx.fillRect(2,8,5,3);if(attackTimer>0){ctx.strokeStyle=stage.accent;ctx.lineWidth=3;ctx.beginPath();ctx.arc(5,0,13,-1,1);ctx.stroke();}ctx.restore();ctx.restore();ctx.fillStyle='#050709';ctx.fillRect(0,230,320,10);}
    function loop(time){const dt=safeDelta(time,previousTime,.034);previousTime=time;update(dt);draw();frame=requestAnimationFrame(loop);}
    return{async mount(host,provided){services=provided;high=services.storage.get('pixelQuest:highScore',0);bestStage=services.storage.get('pixelQuest:bestStage',1);host.innerHTML=markup();root=host.firstElementChild;canvas=root.querySelector('canvas');ctx=createGameContext(canvas,WIDTH,HEIGHT);makeStage(0);state='title';renderUi();previousTime=performance.now();frame=requestAnimationFrame(loop);root.addEventListener('click',event=>{const action=event.target.closest?.('[data-quest]')?.dataset.quest;if(action==='start')start();if(action==='exit')services.exit();});canvas.addEventListener('pointerdown',event=>{const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;if(y<.48)jump();else if(x<.42)held.left=true;else if(x>.58)held.right=true;else attack();});canvas.addEventListener('pointerup',()=>{held.left=held.right=false;});},input(key,down){if(key==='left')held.left=down;if(key==='right')held.right=down;if(!down)return;if((key==='a'||key==='start')&&(state==='title'||state==='over'||state==='win'))start();else if(key==='start'){state=state==='pause'?'play':'pause';renderUi();}else if(state==='play'){if(key==='a'||key==='up')jump();if(key==='b')attack();}if(key==='select')services.exit();},setAuthority(){},unmount(){cancelAnimationFrame(frame);}};
  }
};
