import { createGameContext, safeDelta, smoothToward } from '../../js/render-utils.js?v=2.2.0';

const WIDTH=320,HEIGHT=240,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const WALLS=[[68,72,54,12],[198,72,54,12],[145,45,30,50],[145,145,30,50],[50,142,48,12],[222,142,48,12]];
export default{
  id:'battle-tanks',title:'Battle Tanks',version:'1.0.0',
  create(){
    let root,canvas,ctx,services,frame=0,previousTime=0,state='title',player,enemies=[],shells=[],mines=[],particles=[];
    let wave=1,score=0,high=0,held={left:false,right:false,up:false,down:false},spawnDelay=0;
    const markup=()=>`<div class="tanks-game"><canvas width="640" height="480" aria-label="Battle Tanks arena"></canvas><div class="tanks-hud"><span>WAVE <b id="tanks-wave">01</b></span><span>ARMOR <b id="tanks-armor">100</b></span><span>ENEMY <b id="tanks-enemy">0</b></span><span>HI <b id="tanks-hi">000000</b></span></div><div class="tanks-overlay" id="tanks-overlay"><strong>BATTLE TANKS</strong><small>BREAK THE ARMORED SQUAD<br>ENEMIES AIM, FLANK, AND USE COVER</small><button data-tanks="start">DEPLOY TANK</button><em>D-PAD DRIVE - A FIRE - B MINE</em></div><div class="tanks-pause" id="tanks-pause" hidden>PAUSED</div><button class="tanks-exit" data-tanks="exit" aria-label="Exit game">X</button></div>`;
    const insideWall=(x,y,r=7)=>WALLS.some(w=>x+r>w[0]&&x-r<w[0]+w[2]&&y+r>w[1]&&y-r<w[1]+w[3]);
    function makeTank(x,y,color,ai=false,index=0){return{x,y,vx:0,vy:0,angle:ai?Math.PI/2:-Math.PI/2,turret:ai?Math.PI/2:-Math.PI/2,hp:ai?65+wave*12:100,cooldown:.3+index*.2,ai,color,strafe:index%2?1:-1,think:index*.4,hit:0,mineCooldown:0};}
    function reset(){wave=1;score=0;shells=[];mines=[];particles=[];player=makeTank(160,216,'#f5f7f8');spawnWave();}
    function spawnWave(){enemies=[];const positions=[[35,48],[285,48],[35,116],[285,116],[160,51]];const count=Math.min(5,2+wave);for(let i=0;i<count;i++){const p=positions[i];enemies.push(makeTank(p[0],p[1],['#7894a5','#b2a6c5','#687580','#9a7f91','#b8c4cb'][i],true,i));}spawnDelay=0;updateHud();}
    function updateHud(){if(!root)return;root.querySelector('#tanks-wave').textContent=String(wave).padStart(2,'0');root.querySelector('#tanks-armor').textContent=Math.max(0,Math.ceil(player?.hp||0));root.querySelector('#tanks-enemy').textContent=enemies.filter(e=>e.hp>0).length;root.querySelector('#tanks-hi').textContent=String(high).padStart(6,'0');}
    function show(title,copy,button){const o=root.querySelector('#tanks-overlay');o.hidden=false;o.innerHTML=`<strong>${title}</strong><small>${copy}</small><button data-tanks="start">${button}</button><em>D-PAD DRIVE - A FIRE - B MINE</em>`;}
    function renderUi(){root.querySelector('#tanks-pause').hidden=state!=='pause';if(state==='title')show('BATTLE TANKS','BREAK THE ARMORED SQUAD<br>ENEMIES AIM, FLANK, AND USE COVER','DEPLOY TANK');else if(state==='over')show('TANK DISABLED',`WAVE ${wave} - SCORE ${score}<br>THE SQUAD HELD THE FIELD`,'REDEPLOY');else root.querySelector('#tanks-overlay').hidden=true;updateHud();}
    function start(){reset();state='play';services.tone(155,.09,'sawtooth');renderUi();}
    function moveTank(tank,dx,dy,dt,speed=64){const len=Math.hypot(dx,dy);if(!len)return;tank.angle=Math.atan2(dy,dx);const nx=clamp(tank.x+dx/len*speed*dt,10,310),ny=clamp(tank.y+dy/len*speed*dt,35,230);if(!insideWall(nx,tank.y))tank.x=nx;if(!insideWall(tank.x,ny))tank.y=ny;}
    function fire(tank){if(tank.cooldown>0||tank.hp<=0)return;tank.cooldown=tank.ai?Math.max(.55,1.15-wave*.045):.42;const speed=145;shells.push({x:tank.x+Math.cos(tank.turret)*11,y:tank.y+Math.sin(tank.turret)*11,vx:Math.cos(tank.turret)*speed,vy:Math.sin(tank.turret)*speed,owner:tank.ai?'cpu':'player',life:2.5,bounce:1});services.tone(tank.ai?170:255,.035,'square');}
    function placeMine(){if(state!=='play'||player.mineCooldown>0)return;player.mineCooldown=3.2;mines.push({x:player.x,y:player.y,life:8,armed:.65,owner:'player'});services.tone(120,.04,'square');}
    function burst(x,y,color,count=9){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*100,vy:(Math.random()-.5)*100,life:.5,color});}
    function damage(tank,amount){if(tank.hit>0||tank.hp<=0)return;tank.hp-=amount;tank.hit=.18;burst(tank.x,tank.y,'#e8edf0',6);if(tank.hp<=0){burst(tank.x,tank.y,tank.ai?'#9edaf2':'#fff',22);if(tank.ai){score+=300+wave*50;high=Math.max(high,score);services.storage.set('battleTanks:highScore',high);services.tone(620,.1,'sawtooth');}else{state='over';services.tone(85,.22,'sawtooth');renderUi();}}}
    function lineClear(a,b){const steps=Math.ceil(Math.hypot(b.x-a.x,b.y-a.y)/8);for(let i=1;i<steps;i++){const t=i/steps;if(insideWall(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,2))return false;}return true;}
    function updateEnemy(enemy,dt,index){enemy.cooldown-=dt;enemy.hit=Math.max(0,enemy.hit-dt);const dx=player.x-enemy.x,dy=player.y-enemy.y,d=Math.hypot(dx,dy)||1,target=Math.atan2(dy,dx);let error=Math.sin(enemy.think*1.7+index)*Math.max(.025,.13-wave*.009);enemy.think+=dt;enemy.turret=smoothToward(enemy.turret,target+error,7+wave*.2,dt);let mx=0,my=0;if(d>105){mx=dx;my=dy;}else if(d<65){mx=-dx;my=-dy;}else{mx=-dy*enemy.strafe;my=dx*enemy.strafe;}if(insideWall(enemy.x+mx/d*12,enemy.y+my/d*12)){enemy.strafe*=-1;mx=-my;my=dx*enemy.strafe;}moveTank(enemy,mx,my,dt,43+wave*2);if(d<220&&lineClear(enemy,player)&&Math.abs(Math.atan2(Math.sin(enemy.turret-target),Math.cos(enemy.turret-target)))<.085)fire(enemy);}
    function updateShell(shell,dt){shell.x+=shell.vx*dt;shell.y+=shell.vy*dt;shell.life-=dt;if(shell.x<4||shell.x>316){shell.vx*=-1;shell.bounce-=1;}if(shell.y<31||shell.y>236){shell.vy*=-1;shell.bounce-=1;}const wall=WALLS.find(w=>shell.x>w[0]&&shell.x<w[0]+w[2]&&shell.y>w[1]&&shell.y<w[1]+w[3]);if(wall){if(shell.bounce>0){const dl=Math.abs(shell.x-wall[0]),dr=Math.abs(shell.x-(wall[0]+wall[2])),dtp=Math.abs(shell.y-wall[1]),db=Math.abs(shell.y-(wall[1]+wall[3]));if(Math.min(dl,dr)<Math.min(dtp,db))shell.vx*=-1;else shell.vy*=-1;shell.bounce-=1;}else shell.life=0;}if(shell.owner==='player'){enemies.forEach(enemy=>{if(shell.life>0&&enemy.hp>0&&Math.hypot(shell.x-enemy.x,shell.y-enemy.y)<9){damage(enemy,34);shell.life=0;}});}else if(shell.life>0&&Math.hypot(shell.x-player.x,shell.y-player.y)<9){damage(player,22+wave*2);shell.life=0;}if(shell.bounce<0)shell.life=0;}
    function update(dt){particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;});particles=particles.filter(p=>p.life>0);if(state!=='play')return;player.cooldown-=dt;player.mineCooldown=Math.max(0,player.mineCooldown-dt);player.hit=Math.max(0,player.hit-dt);const dx=(held.right?1:0)-(held.left?1:0),dy=(held.down?1:0)-(held.up?1:0);if(dx||dy){moveTank(player,dx,dy,dt,66);player.turret=smoothToward(player.turret,Math.atan2(dy,dx),12,dt);}enemies.filter(e=>e.hp>0).forEach((enemy,index)=>updateEnemy(enemy,dt,index));shells.forEach(s=>updateShell(s,dt));shells=shells.filter(s=>s.life>0);mines.forEach(m=>{m.life-=dt;m.armed-=dt;if(m.armed<=0){enemies.forEach(enemy=>{if(enemy.hp>0&&Math.hypot(m.x-enemy.x,m.y-enemy.y)<18){damage(enemy,70);m.life=0;burst(m.x,m.y,'#bceaff',18);}});}});mines=mines.filter(m=>m.life>0);if(enemies.length&&enemies.every(e=>e.hp<=0)){spawnDelay+=dt;if(spawnDelay>.9){wave+=1;score+=500;spawnWave();services.tone(780,.12,'triangle');}}updateHud();}
    function drawTank(tank){if(tank.hp<=0)return;ctx.save();ctx.translate(tank.x,tank.y);ctx.rotate(tank.angle);ctx.fillStyle='#050607';ctx.fillRect(-9,-8,18,16);ctx.fillStyle=tank.hit>0?'#fff':tank.color;ctx.fillRect(-7,-6,14,12);ctx.fillStyle='#1a2025';ctx.beginPath();ctx.arc(0,0,5,0,Math.PI*2);ctx.fill();ctx.rotate(tank.turret-tank.angle);ctx.fillStyle=tank.color;ctx.fillRect(0,-2,13,4);ctx.restore();}
    function draw(){ctx.fillStyle='#0b1014';ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.strokeStyle='#ffffff0b';for(let x=0;x<320;x+=16){ctx.beginPath();ctx.moveTo(x,28);ctx.lineTo(x,240);ctx.stroke();}for(let y=32;y<240;y+=16){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(320,y);ctx.stroke();}WALLS.forEach(w=>{ctx.fillStyle='#242c32';ctx.fillRect(...w);ctx.strokeStyle='#8a969f';ctx.strokeRect(w[0]+1,w[1]+1,w[2]-2,w[3]-2);});mines.forEach(m=>{ctx.fillStyle=m.armed>0?'#69747d':'#d8f4ff';ctx.beginPath();ctx.arc(m.x,m.y,5,0,Math.PI*2);ctx.fill();});shells.forEach(s=>{ctx.fillStyle=s.owner==='player'?'#fff':'#91cce5';ctx.beginPath();ctx.arc(s.x,s.y,2.5,0,Math.PI*2);ctx.fill();});enemies.forEach(drawTank);drawTank(player);particles.forEach(p=>{ctx.globalAlpha=clamp(p.life*2,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,2,2);});ctx.globalAlpha=1;}
    function loop(time){const dt=safeDelta(time,previousTime,.034);previousTime=time;update(dt);draw();frame=requestAnimationFrame(loop);}
    return{async mount(host,provided){services=provided;high=services.storage.get('battleTanks:highScore',0);host.innerHTML=markup();root=host.firstElementChild;canvas=root.querySelector('canvas');ctx=createGameContext(canvas,WIDTH,HEIGHT);reset();state='title';renderUi();previousTime=performance.now();frame=requestAnimationFrame(loop);root.addEventListener('click',event=>{const action=event.target.closest?.('[data-tanks]')?.dataset.tanks;if(action==='start')start();if(action==='exit')services.exit();});canvas.addEventListener('pointerdown',event=>{if(state!=='play')return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*WIDTH/rect.width,y=(event.clientY-rect.top)*HEIGHT/rect.height;player.turret=Math.atan2(y-player.y,x-player.x);fire(player);});},input(key,down){if(['left','right','up','down'].includes(key))held[key]=down;if(!down)return;if((key==='a'||key==='start')&&(state==='title'||state==='over'))start();else if(key==='start'){state=state==='pause'?'play':'pause';renderUi();}else if(state==='play'){if(key==='a')fire(player);if(key==='b')placeMine();}if(key==='select')services.exit();},setAuthority(){},unmount(){cancelAnimationFrame(frame);}};
  }
};
