import { createGameContext, safeDelta } from '../../js/render-utils.js?v=3.1.0';

const WIDTH=320,HEIGHT=240,COLS=15,ROWS=9,TILE=18,OX=25,OY=48;
const DIRS=[{x:1,y:0,name:'right'},{x:0,y:1,name:'down'},{x:-1,y:0,name:'left'},{x:0,y:-1,name:'up'}];
const keyFor=(x,y)=>`${x},${y}`;

export default{
  id:'bomb-grid',title:'Bomb Grid',version:'1.0.0',
  create(){
    let root,canvas,ctx,services,frame=0,previousTime=0,state='title';
    let walls,crates,powerups,bombs,flames,players,score=0,wins=0,round=1,moveLock=0;
    const markup=()=>`<div class="bomb-game"><canvas width="640" height="480" aria-label="Bomb Grid arena"></canvas><div class="bomb-hud"><span>ROUND <b id="bomb-round">01</b></span><span>CPU <b id="bomb-cpu">3</b></span><span>WINS <b id="bomb-wins">000</b></span></div><div class="bomb-overlay" id="bomb-overlay"><strong>BOMB GRID</strong><small>OUTSMART THREE GRID HUNTERS<br>BLAST CRATES - CLAIM POWER</small><button data-bomb="start">ENTER GRID</button><em>D-PAD MOVE - A PLACE BOMB</em></div><div class="bomb-pause" id="bomb-pause" hidden>PAUSED</div><button class="bomb-exit" data-bomb="exit" aria-label="Exit game">X</button></div>`;
    const isSolid=(x,y)=>walls.has(keyFor(x,y))||crates.has(keyFor(x,y));
    const bombAt=(x,y)=>bombs.some(b=>b.x===x&&b.y===y);
    function buildArena(){walls=new Set();crates=new Set();powerups=new Map();bombs=[];flames=[];for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){if(x===0||y===0||x===COLS-1||y===ROWS-1||(x%2===0&&y%2===0))walls.add(keyFor(x,y));else if(Math.random()<.57)crates.add(keyFor(x,y));}[[1,1],[2,1],[1,2],[13,7],[12,7],[13,6],[13,1],[12,1],[13,2],[1,7],[2,7],[1,6]].forEach(([x,y])=>crates.delete(keyFor(x,y)));players=[{id:'you',x:1,y:1,alive:true,human:true,range:2,maxBombs:1,color:'#f5f7f8',think:0},{id:'vex',x:13,y:7,alive:true,range:2,maxBombs:1,color:'#ff7895',think:.2},{id:'nova',x:13,y:1,alive:true,range:2,maxBombs:1,color:'#79d9ff',think:.35},{id:'lux',x:1,y:7,alive:true,range:2,maxBombs:1,color:'#c9a5ff',think:.5}];}
    function reset(){score=0;round=1;buildArena();updateHud();}
    function updateHud(){if(!root)return;root.querySelector('#bomb-round').textContent=String(round).padStart(2,'0');root.querySelector('#bomb-cpu').textContent=players?players.filter(p=>p.alive&&!p.human).length:3;root.querySelector('#bomb-wins').textContent=String(wins).padStart(3,'0');}
    function show(title,copy,button){const overlay=root.querySelector('#bomb-overlay');overlay.hidden=false;overlay.innerHTML=`<strong>${title}</strong><small>${copy}</small><button data-bomb="start">${button}</button><em>D-PAD MOVE - A PLACE BOMB</em>`;}
    function renderUi(){root.querySelector('#bomb-pause').hidden=state!=='pause';if(state==='title')show('BOMB GRID','OUTSMART THREE GRID HUNTERS<br>BLAST CRATES - CLAIM POWER','ENTER GRID');else if(state==='over')show('GRID DEFEAT',`${score} POINTS<br>THE HUNTERS CONTROL THE GRID`,'REMATCH');else if(state==='win')show('GRID MASTER',`${score} POINTS<br>ALL CPU HUNTERS DEFEATED`,'NEXT ROUND');else root.querySelector('#bomb-overlay').hidden=true;updateHud();}
    function start(){if(state==='win')buildArena();else reset();state='play';services.tone(260,.06,'square');renderUi();}
    function actorAt(x,y){return players.find(p=>p.alive&&p.x===x&&p.y===y);}
    function move(actor,dir){if(!actor?.alive)return false;const nx=actor.x+dir.x,ny=actor.y+dir.y;if(isSolid(nx,ny)||bombAt(nx,ny)||actorAt(nx,ny))return false;actor.x=nx;actor.y=ny;const power=powerups.get(keyFor(nx,ny));if(power){if(power==='range')actor.range=Math.min(5,actor.range+1);else actor.maxBombs=Math.min(3,actor.maxBombs+1);powerups.delete(keyFor(nx,ny));services.tone(670,.05,'triangle');}return true;}
    function placeBomb(actor){if(!actor?.alive)return;const active=bombs.filter(b=>b.owner===actor.id).length;if(active>=actor.maxBombs||bombAt(actor.x,actor.y))return;bombs.push({x:actor.x,y:actor.y,owner:actor.id,fuse:1.75,range:actor.range});services.tone(155,.035,'square');}
    function blastTiles(bomb){const tiles=[[bomb.x,bomb.y]];DIRS.forEach(dir=>{for(let step=1;step<=bomb.range;step++){const x=bomb.x+dir.x*step,y=bomb.y+dir.y*step,key=keyFor(x,y);if(walls.has(key))break;tiles.push([x,y]);if(crates.has(key))break;}});return tiles;}
    function explode(bomb){blastTiles(bomb).forEach(([x,y])=>{const key=keyFor(x,y);flames.push({x,y,life:.46});if(crates.delete(key)){score+=10;if(Math.random()<.28)powerups.set(key,Math.random()<.55?'range':'bomb');}players.forEach(player=>{if(player.alive&&player.x===x&&player.y===y){player.alive=false;if(player.human){state='over';services.tone(90,.2,'sawtooth');}else{score+=250;services.tone(720,.07,'triangle');}}});const chained=bombs.find(other=>other!==bomb&&other.x===x&&other.y===y);if(chained)chained.fuse=0;});services.tone(105,.1,'square');}
    function dangerSet(){const danger=new Set();bombs.forEach(bomb=>blastTiles(bomb).forEach(([x,y])=>danger.add(keyFor(x,y))));flames.forEach(flame=>danger.add(keyFor(flame.x,flame.y)));return danger;}
    function distanceMap(tx,ty){const distances=new Map([[keyFor(tx,ty),0]]),queue=[[tx,ty]];for(let i=0;i<queue.length;i++){const [x,y]=queue[i],d=distances.get(keyFor(x,y));DIRS.forEach(dir=>{const nx=x+dir.x,ny=y+dir.y,key=keyFor(nx,ny);if(!distances.has(key)&&!isSolid(nx,ny)){distances.set(key,d+1);queue.push([nx,ny]);}});}return distances;}
    function cpuThink(cpu){if(!cpu.alive)return;const human=players[0],danger=dangerSet();const options=DIRS.filter(dir=>!isSolid(cpu.x+dir.x,cpu.y+dir.y)&&!bombAt(cpu.x+dir.x,cpu.y+dir.y)&&!actorAt(cpu.x+dir.x,cpu.y+dir.y));const threatened=danger.has(keyFor(cpu.x,cpu.y));let choices=options.filter(dir=>!danger.has(keyFor(cpu.x+dir.x,cpu.y+dir.y)));if(!choices.length)choices=options;if(!choices.length)return;const map=human.alive?distanceMap(human.x,human.y):new Map();choices.sort((a,b)=>(map.get(keyFor(cpu.x+a.x,cpu.y+a.y))??99)-(map.get(keyFor(cpu.x+b.x,cpu.y+b.y))??99));const adjacentCrate=DIRS.some(dir=>crates.has(keyFor(cpu.x+dir.x,cpu.y+dir.y)));const lineUp=human.alive&&(cpu.x===human.x||cpu.y===human.y)&&Math.abs(cpu.x-human.x)+Math.abs(cpu.y-human.y)<=cpu.range+1;if(!threatened&&(lineUp||adjacentCrate&&Math.random()<.42))placeBomb(cpu);else move(cpu,threatened?choices[Math.floor(Math.random()*choices.length)]:choices[0]);}
    function checkRound(){if(state!=='play')return;if(!players[0].alive){renderUi();return;}if(players.filter(p=>p.alive&&!p.human).length===0){state='win';wins+=1;round+=1;score+=1000;services.storage.set('bombGrid:wins',wins);services.tone(900,.14,'triangle');renderUi();}}
    function update(dt){if(state!=='play')return;moveLock=Math.max(0,moveLock-dt);bombs.forEach(b=>b.fuse-=dt);const detonated=bombs.filter(b=>b.fuse<=0);bombs=bombs.filter(b=>b.fuse>0);detonated.forEach(explode);flames.forEach(f=>f.life-=dt);flames=flames.filter(f=>f.life>0);players.filter(p=>!p.human).forEach(cpu=>{cpu.think-=dt;if(cpu.think<=0){cpuThink(cpu);cpu.think=Math.max(.12,.3-round*.015)+Math.random()*.09;}});const danger=dangerSet();players.forEach(player=>{if(player.alive&&danger.has(keyFor(player.x,player.y))){player.alive=false;if(player.human)state='over';else score+=250;}});if(state==='over'){renderUi();return;}checkRound();updateHud();}
    function draw(){ctx.fillStyle='#07090b';ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#172129';ctx.fillRect(OX,OY,COLS*TILE,ROWS*TILE);for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){const px=OX+x*TILE,py=OY+y*TILE,key=keyFor(x,y);ctx.fillStyle=(x+y)%2?'#1b2830':'#202f38';ctx.fillRect(px,py,TILE,TILE);if(walls.has(key)){ctx.fillStyle='#080b0d';ctx.fillRect(px+1,py+1,TILE-2,TILE-2);ctx.strokeStyle='#6d7982';ctx.strokeRect(px+3,py+3,TILE-6,TILE-6);}else if(crates.has(key)){ctx.fillStyle='#6e7780';ctx.fillRect(px+2,py+2,TILE-4,TILE-4);ctx.strokeStyle='#d7dde1';ctx.beginPath();ctx.moveTo(px+3,py+3);ctx.lineTo(px+TILE-3,py+TILE-3);ctx.moveTo(px+TILE-3,py+3);ctx.lineTo(px+3,py+TILE-3);ctx.stroke();}const power=powerups.get(key);if(power){ctx.fillStyle=power==='range'?'#8ddfff':'#d8b9ff';ctx.beginPath();ctx.arc(px+9,py+9,5,0,Math.PI*2);ctx.fill();}}
      bombs.forEach(b=>{const x=OX+b.x*TILE+9,y=OY+b.y*TILE+9;ctx.fillStyle='#050607';ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle=b.fuse<.55?'#fff':'#7f8b94';ctx.stroke();ctx.fillStyle='#fff';ctx.fillRect(x+3,y-7,2,3);});flames.forEach(f=>{ctx.globalAlpha=Math.min(1,f.life*4);ctx.fillStyle='#eaf8ff';ctx.fillRect(OX+f.x*TILE+2,OY+f.y*TILE+2,TILE-4,TILE-4);ctx.fillStyle='#75c6e8';ctx.fillRect(OX+f.x*TILE+6,OY+f.y*TILE+6,TILE-12,TILE-12);});ctx.globalAlpha=1;players.forEach(player=>{if(!player.alive)return;const x=OX+player.x*TILE+9,y=OY+player.y*TILE+9;ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(x,y+5,7,3,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=player.color;ctx.beginPath();ctx.roundRect(x-6,y-7,12,13,3);ctx.fill();ctx.fillStyle='#080a0c';ctx.fillRect(x-2,y-3,4,4);});}
    function loop(time){const dt=safeDelta(time,previousTime,.05);previousTime=time;update(dt);draw();frame=requestAnimationFrame(loop);}
    return{async mount(host,provided){services=provided;wins=services.storage.get('bombGrid:wins',0);host.innerHTML=markup();root=host.firstElementChild;canvas=root.querySelector('canvas');ctx=createGameContext(canvas,WIDTH,HEIGHT);reset();state='title';renderUi();previousTime=performance.now();frame=requestAnimationFrame(loop);root.addEventListener('click',event=>{const action=event.target.closest?.('[data-bomb]')?.dataset.bomb;if(action==='start')start();if(action==='exit')services.exit();});canvas.addEventListener('pointerdown',event=>{if(state!=='play')return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*WIDTH/rect.width-(OX+players[0].x*TILE+9),y=(event.clientY-rect.top)*HEIGHT/rect.height-(OY+players[0].y*TILE+9);move(players[0],Math.abs(x)>Math.abs(y)?DIRS[x>0?0:2]:DIRS[y>0?1:3]);});},input(key,down){if(!down)return;if((key==='a'||key==='start')&&(state==='title'||state==='over'||state==='win'))start();else if(key==='start'){state=state==='pause'?'play':'pause';renderUi();}else if(state==='play'){const dir=DIRS.find(item=>item.name===key);if(dir)move(players[0],dir);if(key==='a')placeBomb(players[0]);}if(key==='select')services.exit();},setAuthority(){},unmount(){cancelAnimationFrame(frame);}};
  }
};
