import { createGameContext, safeDelta } from '../../js/render-utils.js?v=3.1.0';

const WIDTH=320,HEIGHT=240,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const PIN_LAYOUT=[[160,65],[151,75],[169,75],[142,85],[160,85],[178,85],[133,95],[151,95],[169,95],[187,95]];
export default{
  id:'pocket-bowling',title:'Pocket Bowling',version:'1.0.0',
  create(){
    let root,canvas,ctx,services,frame=0,previousTime=0,state='title',pins=[],ball=null,particles=[];
    let frameIndex=0,rollInFrame=0,tenthRolls=[],rolls=[],aim=160,power=.65,hook=0,best=0,cpuScore=0,message='',resultTimer=0,pendingKnocked=0;
    const markup=()=>`<div class="bowling-game"><canvas width="640" height="480" aria-label="Pocket Bowling lane"></canvas><div class="bowling-hud"><span>FRAME <b id="bowling-frame">01/10</b></span><span>KSR <b id="bowling-score">000</b></span><span>CPU <b id="bowling-cpu">000</b></span><span>BEST <b id="bowling-best">000</b></span></div><div class="bowling-message" id="bowling-message"></div><div class="bowling-meter"><i id="bowling-power"></i><b id="bowling-aim"></b></div><div class="bowling-overlay" id="bowling-overlay"><strong>POCKET BOWLING</strong><small>TEN FRAME PRO MATCH<br>CONTROL AIM, POWER, AND HOOK</small><button data-bowling="start">START MATCH</button><em>LEFT / RIGHT AIM - UP/DOWN POWER - A ROLL - B HOOK</em></div><div class="bowling-pause" id="bowling-pause" hidden>PAUSED</div><button class="bowling-exit" data-bowling="exit" aria-label="Exit game">X</button></div>`;
    function resetPins(){pins=PIN_LAYOUT.map(([x,y],index)=>({x,y,standing:true,vx:0,vy:0,angle:0,index}));}
    function reset(){frameIndex=0;rollInFrame=0;tenthRolls=[];rolls=[];aim=160;power=.65;hook=0;cpuScore=0;ball=null;particles=[];resultTimer=0;message='FRAME 1';resetPins();}
    function bowlingScore(){let total=0,index=0;for(let frame=0;frame<10;frame++){if(index>=rolls.length)break;if(rolls[index]===10){if(index+2<rolls.length)total+=10+rolls[index+1]+rolls[index+2];else total+=10;index+=1;}else{const first=rolls[index]||0,second=rolls[index+1]||0;if(first+second===10){total+=10+(rolls[index+2]||0);}else total+=first+second;index+=2;}}return total;}
    function updateHud(){if(!root)return;root.querySelector('#bowling-frame').textContent=`${String(Math.min(10,frameIndex+1)).padStart(2,'0')}/10`;root.querySelector('#bowling-score').textContent=String(bowlingScore()).padStart(3,'0');root.querySelector('#bowling-cpu').textContent=String(cpuScore).padStart(3,'0');root.querySelector('#bowling-best').textContent=String(best).padStart(3,'0');root.querySelector('#bowling-power').style.width=`${power*100}%`;root.querySelector('#bowling-aim').style.left=`${((aim-122)/76)*100}%`;root.querySelector('#bowling-message').textContent=message;}
    function show(title,copy,button){const o=root.querySelector('#bowling-overlay');o.hidden=false;o.innerHTML=`<strong>${title}</strong><small>${copy}</small><button data-bowling="start">${button}</button><em>LEFT / RIGHT AIM - UP/DOWN POWER - A ROLL - B HOOK</em>`;}
    function renderUi(){root.querySelector('#bowling-pause').hidden=state!=='pause';if(state==='title')show('POCKET BOWLING',`TEN FRAME PRO MATCH<br>PERSONAL BEST ${best}`,'START MATCH');else if(state==='over')show(bowlingScore()>cpuScore?'KSR WINS':bowlingScore()===cpuScore?'MATCH TIED':'CPU WINS',`${bowlingScore()} - ${cpuScore}<br>${bowlingScore()>cpuScore?'LANE CHAMPION':'THE CPU OWNED THE POCKET'}`,'BOWL AGAIN');else root.querySelector('#bowling-overlay').hidden=true;updateHud();}
    function start(){reset();state='play';services.tone(330,.07,'square');renderUi();}
    function standingPins(){return pins.filter(pin=>pin.standing);}
    function rollBall(){if(state!=='play'||ball||resultTimer>0)return;ball={x:160,y:218,vx:(aim-160)*.3,vy:-(118+power*82),curve:hook*(12+power*15),spin:0};message=hook===0?'STRAIGHT BALL':hook<0?'LEFT HOOK':'RIGHT HOOK';services.tone(145,.05,'triangle');}
    function knockPins(){const deckX=ball.x,accuracy=clamp(1-Math.abs(deckX-160)/48,0,1),standing=standingPins();let count=Math.floor(accuracy*6.8+power*2.6+Math.random()*2.1);if(accuracy>.91&&power>.72&&Math.random()<.78)count=10;count=Math.min(standing.length,Math.max(0,count));standing.sort((a,b)=>Math.abs(a.x-deckX)-Math.abs(b.x-deckX));standing.slice(0,count).forEach((pin,index)=>{pin.standing=false;pin.vx=(pin.x-deckX)*2.2+(Math.random()-.5)*45;pin.vy=-25-Math.random()*55;pin.angle=(Math.random()-.5)*2;});pendingKnocked=count;resultTimer=.9;for(let i=0;i<count*2;i++)particles.push({x:deckX+(Math.random()-.5)*25,y:82+(Math.random()-.5)*20,vx:(Math.random()-.5)*60,vy:(Math.random()-.5)*50,life:.4});message=count===10?'STRIKE!':standing.length===count&&rollInFrame>0?'SPARE!':`${count} PINS`;services.tone(count===10?850:240+count*35,.08,count===10?'triangle':'square');}
    function cpuFrame(){const roll=Math.random();let add;if(roll<.34)add=14+Math.floor(Math.random()*9);else if(roll<.76)add=9+Math.floor(Math.random()*7);else add=7+Math.floor(Math.random()*4);cpuScore=Math.min(300,cpuScore+add);}
    function finishGame(){state='over';const total=bowlingScore();if(total>best){best=total;services.storage.set('pocketBowling:bestScore',best);}services.tone(total>cpuScore?880:115,.15,total>cpuScore?'triangle':'sawtooth');renderUi();}
    function completeRoll(){rolls.push(pendingKnocked);if(frameIndex<9){if(rollInFrame===0&&pendingKnocked===10){cpuFrame();frameIndex+=1;rollInFrame=0;resetPins();}else if(rollInFrame===0){rollInFrame=1;}else{cpuFrame();frameIndex+=1;rollInFrame=0;resetPins();}}else{tenthRolls.push(pendingKnocked);if(tenthRolls.length===1){rollInFrame=1;if(pendingKnocked===10)resetPins();}else if(tenthRolls.length===2){const first=tenthRolls[0],second=tenthRolls[1];if(first===10){rollInFrame=2;if(second===10)resetPins();}else if(first+second===10){rollInFrame=2;resetPins();}else{cpuFrame();finishGame();return;}}else{cpuFrame();finishGame();return;}}ball=null;pendingKnocked=0;resultTimer=0;if(frameIndex>=10)finishGame();else{message=`FRAME ${frameIndex+1} - ROLL ${rollInFrame+1}`;updateHud();}}
    function update(dt){particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;});particles=particles.filter(p=>p.life>0);pins.forEach(pin=>{if(!pin.standing){pin.x+=pin.vx*dt;pin.y+=pin.vy*dt;pin.vy+=90*dt;pin.vx*=Math.pow(.96,dt*60);pin.angle+=dt*3;}});if(state!=='play')return;if(resultTimer>0){resultTimer-=dt;if(resultTimer<=0)completeRoll();return;}if(ball){ball.spin+=dt*8;ball.y+=ball.vy*dt;ball.x+=ball.vx*dt+ball.curve*dt*(1-(ball.y-62)/156);ball.vx+=ball.curve*dt*.35;if(ball.y<=92){knockPins();ball.y=92;}}updateHud();}
    function laneHalf(y){return 27+(y-42)/176*92;}
    function drawPin(pin){ctx.save();ctx.translate(pin.x,pin.y);ctx.rotate(pin.angle);ctx.fillStyle='#f7f8f9';ctx.beginPath();ctx.ellipse(0,0,3.4,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#758b99';ctx.fillRect(-3,-1,6,2);ctx.restore();}
    function draw(){const bg=ctx.createLinearGradient(0,0,0,HEIGHT);bg.addColorStop(0,'#0b0e12');bg.addColorStop(1,'#222b32');ctx.fillStyle=bg;ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#13191e';ctx.fillRect(17,35,286,196);const lane=ctx.createLinearGradient(0,40,0,228);lane.addColorStop(0,'#d9dde0');lane.addColorStop(1,'#777f84');ctx.fillStyle=lane;ctx.beginPath();ctx.moveTo(133,42);ctx.lineTo(187,42);ctx.lineTo(278,229);ctx.lineTo(42,229);ctx.closePath();ctx.fill();ctx.strokeStyle='#f8fafb';ctx.beginPath();ctx.moveTo(133,42);ctx.lineTo(42,229);ctx.moveTo(187,42);ctx.lineTo(278,229);ctx.stroke();ctx.strokeStyle='#39444b';for(let i=1;i<7;i++){const x=160+(i-3.5)*16;ctx.beginPath();ctx.moveTo(160+(x-160)*.25,42);ctx.lineTo(x,229);ctx.stroke();}ctx.fillStyle='#4d5961';ctx.fillRect(126,102,68,2);pins.forEach(drawPin);particles.forEach(p=>{ctx.globalAlpha=clamp(p.life*3,0,1);ctx.fillStyle='#e9f6fb';ctx.fillRect(p.x,p.y,2,2);});ctx.globalAlpha=1;if(ball){ctx.save();ctx.translate(ball.x,ball.y);ctx.rotate(ball.spin);ctx.fillStyle='#10151a';ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#9eddf5';ctx.beginPath();ctx.arc(-2,-2,1.2,0,Math.PI*2);ctx.arc(2,-2,1.2,0,Math.PI*2);ctx.fill();ctx.restore();}else{ctx.fillStyle='#10151a';ctx.beginPath();ctx.arc(160,218,7,0,Math.PI*2);ctx.fill();}ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(160,218);ctx.lineTo(aim,117);ctx.stroke();}
    function loop(time){const dt=safeDelta(time,previousTime,.034);previousTime=time;update(dt);draw();frame=requestAnimationFrame(loop);}
    return{async mount(host,provided){services=provided;best=services.storage.get('pocketBowling:bestScore',0);host.innerHTML=markup();root=host.firstElementChild;canvas=root.querySelector('canvas');ctx=createGameContext(canvas,WIDTH,HEIGHT);reset();state='title';renderUi();previousTime=performance.now();frame=requestAnimationFrame(loop);root.addEventListener('click',event=>{const action=event.target.closest?.('[data-bowling]')?.dataset.bowling;if(action==='start')start();if(action==='exit')services.exit();});canvas.addEventListener('pointerdown',event=>{if(state!=='play'||ball)return;const rect=canvas.getBoundingClientRect();aim=clamp(122+(event.clientX-rect.left)/rect.width*76,122,198);rollBall();});},input(key,down){if(!down)return;if((key==='a'||key==='start')&&(state==='title'||state==='over'))start();else if(key==='start'){state=state==='pause'?'play':'pause';renderUi();}else if(state==='play'&&!ball&&resultTimer<=0){if(key==='left')aim=clamp(aim-4,122,198);if(key==='right')aim=clamp(aim+4,122,198);if(key==='up')power=clamp(power+.07,.25,1);if(key==='down')power=clamp(power-.07,.25,1);if(key==='b')hook=hook===0?1:hook===1?-1:0;if(key==='a')rollBall();}if(key==='select')services.exit();updateHud();},setAuthority(){},unmount(){cancelAnimationFrame(frame);}};
  }
};
