import { createGameContext, safeDelta, smoothToward } from '../../js/render-utils.js?v=3.0.0';

const WIDTH=320,HEIGHT=240,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export default{
  id:'street-hoops',title:'Street Hoops',version:'1.0.0',
  create(){
    let root,canvas,ctx,services,frame=0,previousTime=0,state='title',playerX=84,targetX=84,defenderX=168,defenderY=190;
    let ball=null,charging=false,power=.2,powerDir=1,aim=0,clock=45,playerScore=0,cpuScore=0,high=0,wins=0,cpuTimer=2.2,resultTimer=0,message='',held={left:false,right:false};
    const markup=()=>`<div class="hoops-game"><canvas width="640" height="480" aria-label="Street Hoops court"></canvas><div class="hoops-hud"><span>KSR <b id="hoops-player">00</b></span><strong id="hoops-clock">00:45</strong><span>CPU <b id="hoops-cpu">00</b></span></div><div class="hoops-message" id="hoops-message"></div><div class="hoops-meter"><i id="hoops-power"></i><b></b></div><div class="hoops-overlay" id="hoops-overlay"><strong>STREET HOOPS</strong><small>45 SECOND CPU SHOOTOUT<br>THE DEFENDER READS YOUR RELEASE</small><button data-hoops="start">TAKE THE COURT</button><em>LEFT / RIGHT MOVE - UP/DOWN AIM - A POWER/RELEASE - B DUNK</em></div><div class="hoops-pause" id="hoops-pause" hidden>PAUSED</div><button class="hoops-exit" data-hoops="exit" aria-label="Exit game">X</button></div>`;
    function reset(){playerX=targetX=76;defenderX=166;defenderY=190;ball=null;charging=false;power=.2;powerDir=1;aim=0;clock=45;playerScore=cpuScore=0;cpuTimer=1.8;resultTimer=0;message='FIRST TO THE LEAD';held={left:false,right:false};}
    function updateHud(){if(!root)return;root.querySelector('#hoops-player').textContent=String(playerScore).padStart(2,'0');root.querySelector('#hoops-cpu').textContent=String(cpuScore).padStart(2,'0');root.querySelector('#hoops-clock').textContent=`00:${String(Math.ceil(clock)).padStart(2,'0')}`;root.querySelector('#hoops-message').textContent=message;root.querySelector('#hoops-power').style.width=`${power*100}%`;}
    function show(title,copy,button){const o=root.querySelector('#hoops-overlay');o.hidden=false;o.innerHTML=`<strong>${title}</strong><small>${copy}</small><button data-hoops="start">${button}</button><em>LEFT / RIGHT MOVE - UP/DOWN AIM - A POWER/RELEASE - B DUNK</em>`;}
    function renderUi(){root.querySelector('#hoops-pause').hidden=state!=='pause';if(state==='title')show('STREET HOOPS',`45 SECOND CPU SHOOTOUT<br>HIGH ${high} - ${wins} TOURNAMENT WINS`,'TAKE THE COURT');else if(state==='over')show(playerScore>cpuScore?'KSR WINS':playerScore===cpuScore?'OVERTIME DRAW':'CPU WINS',`${playerScore} - ${cpuScore}<br>${playerScore>cpuScore?'COURT CONTROLLED':'THE CPU NEVER MISSED TWICE'}`,'REMATCH');else root.querySelector('#hoops-overlay').hidden=true;updateHud();}
    function start(){reset();state='play';services.tone(430,.07,'square');renderUi();}
    function beginCharge(){if(state!=='play'||ball||resultTimer>0)return;if(!charging){charging=true;message='SET POWER';services.tone(280,.025);}else shoot();}
    function shoot(){if(!charging)return;charging=false;const startY=184,hoopY=79,vy=-238-power*88,g=250,dy=startY-hoopY,disc=Math.max(1,vy*vy-2*g*dy),time=(-vy+Math.sqrt(disc))/g;const target=257+(power-.72)*74+aim*25;ball={x:playerX+6,y:startY,vx:(target-(playerX+6))/time,vy,g,previousY:startY,points:playerX<112?3:2,blocked:false};message=ball.points===3?'THREE POINT SHOT':'TWO POINT SHOT';services.tone(205+power*160,.04,'triangle');}
    function dunk(){if(state!=='play'||ball||resultTimer>0)return;if(playerX<185){targetX=Math.min(210,playerX+30);message='MOVE CLOSER';return;}const defended=Math.abs(defenderX-playerX)<26&&Math.random()<.62;if(defended){message='CPU REJECTED';services.tone(95,.08,'square');}else{playerScore+=2;message='KSR SLAM';services.tone(760,.09,'triangle');}resultTimer=.7;}
    function scoreCpu(){const pressure=Math.max(0,(playerScore-cpuScore)*.018),chance=clamp(.7+pressure,.68,.86);if(Math.random()<chance){const points=Math.random()<.32?3:2;cpuScore+=points;message=`CPU +${points}`;services.tone(135,.035,'square');}else message='CPU MISSED';cpuTimer=1.85+Math.random()*.75;}
    function finish(){state='over';high=Math.max(high,playerScore);services.storage.set('streetHoops:highScore',high);if(playerScore>cpuScore){wins+=1;services.storage.set('streetHoops:wins',wins);services.tone(850,.14,'triangle');}else services.tone(105,.16,'sawtooth');renderUi();}
    function updateBall(dt){if(!ball)return;ball.previousY=ball.y;ball.x+=ball.vx*dt;ball.y+=ball.vy*dt;ball.vy+=ball.g*dt;defenderY=smoothToward(defenderY,ball.x>defenderX&&ball.y<170?159:190,7,dt);if(!ball.blocked&&ball.y>defenderY-24&&ball.y<defenderY+8&&Math.abs(ball.x-defenderX)<13){ball.blocked=true;ball.vx*=-.45;ball.vy=55;message='SHOT BLOCKED';services.tone(95,.06,'square');}if(ball.previousY<79&&ball.y>=79&&ball.vy>0){if(ball.x>248&&ball.x<269){playerScore+=ball.points;message=ball.points===3?'KSR THREE!':'BUCKET!';services.tone(790,.08,'triangle');}else{message='OFF THE RIM';services.tone(155,.05,'square');}resultTimer=.72;}if(ball.y>228||ball.x>330||ball.x<-10){if(resultTimer<=0){message='MISSED';resultTimer=.5;}ball=null;}}
    function update(dt){if(state!=='play')return;clock-=dt;if(clock<=0){clock=0;finish();return;}resultTimer=Math.max(0,resultTimer-dt);const move=(held.right?1:0)-(held.left?1:0);if(move)targetX+=move*105*dt;targetX=clamp(targetX,43,213);playerX=smoothToward(playerX,targetX,11,dt);defenderX=smoothToward(defenderX,clamp(playerX+58,128,218),5.5,dt);if(charging){power+=powerDir*dt*1.35;if(power>=1){power=1;powerDir=-1;}if(power<=.08){power=.08;powerDir=1;}}updateBall(dt);cpuTimer-=dt;if(cpuTimer<=0)scoreCpu();updateHud();}
    function drawPlayer(x,y,cpu=false){ctx.save();ctx.translate(x,y);ctx.fillStyle='#05060766';ctx.beginPath();ctx.ellipse(0,15,11,4,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=cpu?'#71899a':'#f4f6f7';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-3,2);ctx.lineTo(-7,15);ctx.moveTo(3,2);ctx.lineTo(8,15);ctx.stroke();ctx.fillStyle=cpu?'#202b33':'#f4f6f7';ctx.beginPath();ctx.roundRect(-8,-13,16,18,4);ctx.fill();ctx.fillStyle=cpu?'#c3cbd0':'#101418';ctx.beginPath();ctx.arc(0,-18,6,0,Math.PI*2);ctx.fill();ctx.restore();}
    function draw(){const sky=ctx.createLinearGradient(0,0,0,130);sky.addColorStop(0,'#1a2630');sky.addColorStop(1,'#718995');ctx.fillStyle=sky;ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#151b20';for(let x=0,i=0;x<320;i++){const w=20+(i*9)%28,h=25+(i*17)%45;ctx.fillRect(x,104-h,w,h);ctx.fillStyle='#9fd0e344';ctx.fillRect(x+5,75-h,3,5);ctx.fillStyle='#151b20';x+=w+2;}ctx.fillStyle='#313a40';ctx.fillRect(0,106,320,134);ctx.strokeStyle='#aeb9bf';ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(257,202,82,Math.PI,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.moveTo(0,202);ctx.lineTo(320,202);ctx.stroke();ctx.fillStyle='#dce3e6';ctx.fillRect(277,42,5,76);ctx.fillRect(247,53,31,23);ctx.strokeStyle='#fff';ctx.beginPath();ctx.moveTo(247,79);ctx.lineTo(270,79);ctx.stroke();ctx.strokeStyle='#84949d';ctx.beginPath();ctx.arc(258,81,11,0,Math.PI);ctx.stroke();drawPlayer(playerX,190,false);drawPlayer(defenderX,defenderY,true);if(ball){ctx.fillStyle='#d7dde1';ctx.beginPath();ctx.arc(ball.x,ball.y,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#36434b';ctx.beginPath();ctx.arc(ball.x,ball.y,5,0,Math.PI*2);ctx.moveTo(ball.x-5,ball.y);ctx.lineTo(ball.x+5,ball.y);ctx.stroke();}else{ctx.fillStyle='#d7dde1';ctx.beginPath();ctx.arc(playerX+8,181,5,0,Math.PI*2);ctx.fill();}}
    function loop(time){const dt=safeDelta(time,previousTime,.034);previousTime=time;update(dt);draw();frame=requestAnimationFrame(loop);}
    return{async mount(host,provided){services=provided;high=services.storage.get('streetHoops:highScore',0);wins=services.storage.get('streetHoops:wins',0);host.innerHTML=markup();root=host.firstElementChild;canvas=root.querySelector('canvas');ctx=createGameContext(canvas,WIDTH,HEIGHT);reset();state='title';renderUi();previousTime=performance.now();frame=requestAnimationFrame(loop);root.addEventListener('click',event=>{const action=event.target.closest?.('[data-hoops]')?.dataset.hoops;if(action==='start')start();if(action==='exit')services.exit();});canvas.addEventListener('pointerdown',event=>{if(state!=='play')return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)*WIDTH/rect.width;targetX=clamp(x,43,213);beginCharge();});},input(key,down){if(key==='left')held.left=down;if(key==='right')held.right=down;if(!down)return;if((key==='a'||key==='start')&&(state==='title'||state==='over'))start();else if(key==='start'){state=state==='pause'?'play':'pause';renderUi();}else if(state==='play'){if(key==='up')aim=clamp(aim-.08,-.45,.45);if(key==='down')aim=clamp(aim+.08,-.45,.45);if(key==='a')beginCharge();if(key==='b')dunk();}if(key==='select')services.exit();},setAuthority(){},unmount(){cancelAnimationFrame(frame);}};
  }
};
