const W=24,H=14,CELL=10;
export default{id:'snake',title:'Snake Byte',version:'1.0.0',create(){
  let root,canvas,ctx,services,timer=null,state='title',score=0,high=0,snake=[],food={},dir={x:1,y:0},nextDir={x:1,y:0},speed=145;
  const html=()=>`<div class="snake-game"><div class="snake-hud"><span>SCORE <b id="snake-score">0000</b></span><span>HI <b id="snake-hi">0000</b></span></div><canvas width="240" height="140" aria-label="Snake game board"></canvas><div class="snake-overlay" id="snake-overlay"><strong>SNAKE BYTE</strong><small>THE NEON GARDEN</small><button data-snake="start">START GAME</button><em>START / A</em></div><button class="snake-exit" data-snake="exit" aria-label="Exit game">×</button><div class="snake-pause" id="snake-pause" hidden>PAUSED</div></div>`;
  function updateHud(){root.querySelector('#snake-score').textContent=String(score).padStart(4,'0');root.querySelector('#snake-hi').textContent=String(high).padStart(4,'0')}
  function spawn(){do{food={x:Math.floor(Math.random()*W),y:Math.floor(Math.random()*H)}}while(snake.some(p=>p.x===food.x&&p.y===food.y))}
  function reset(){score=0;speed=145;snake=[{x:8,y:7},{x:7,y:7},{x:6,y:7}];dir=nextDir={x:1,y:0};spawn();updateHud()}
  function draw(){ctx.fillStyle='#101b18';ctx.fillRect(0,0,240,140);ctx.fillStyle='#182721';for(let x=0;x<W;x+=2)for(let y=0;y<H;y+=2)ctx.fillRect(x*CELL,y*CELL,1,1);ctx.fillStyle='#ffcf4a';ctx.fillRect(food.x*CELL+2,food.y*CELL+2,6,6);ctx.fillStyle='#59d67d';snake.forEach((p,i)=>{ctx.fillStyle=i?'#43b967':'#9af5aa';ctx.fillRect(p.x*CELL+1,p.y*CELL+1,8,8)});}
  function loop(){clearTimeout(timer);if(state!=='play')return;dir=nextDir;const head={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(head.x<0||head.x>=W||head.y<0||head.y>=H||snake.some(p=>p.x===head.x&&p.y===head.y)){gameOver();return}snake.unshift(head);if(head.x===food.x&&head.y===food.y){score+=10;high=Math.max(high,score);services.storage.set('snake:highScore',high);speed=Math.max(55,145-Math.floor(score/40)*10);spawn();services.tone(760,.045);updateHud()}else snake.pop();draw();timer=setTimeout(loop,speed)}
  function start(){reset();state='play';root.querySelector('#snake-overlay').hidden=true;root.querySelector('#snake-pause').hidden=true;services.tone(520,.06);draw();loop()}
  function gameOver(){state='over';clearTimeout(timer);high=Math.max(high,score);services.storage.set('snake:highScore',high);services.tone(150,.22,'sawtooth');const o=root.querySelector('#snake-overlay');o.hidden=false;o.innerHTML=`<strong>GAME OVER</strong><small>SCORE ${String(score).padStart(4,'0')}</small><button data-snake="start">RESTART</button><em>A / START</em>`}
  function pause(){if(state==='play'){state='pause';clearTimeout(timer);root.querySelector('#snake-pause').hidden=false;services.tone(300,.04)}else if(state==='pause'){state='play';root.querySelector('#snake-pause').hidden=true;loop()}}
  function move(x,y){if(state!=='play')return;if(x!==-dir.x||y!==-dir.y)nextDir={x,y}}
  return{async mount(host,s){services=s;high=s.storage.get('snake:highScore',0);host.innerHTML=html();root=host.firstElementChild;canvas=root.querySelector('canvas');ctx=canvas.getContext('2d');reset();draw();root.addEventListener('click',e=>{const a=e.target.dataset.snake;if(a==='start')start();if(a==='exit'){clearTimeout(timer);services.exit()}})},input(key,down){if(!down)return;if(key==='up')move(0,-1);if(key==='down')move(0,1);if(key==='left')move(-1,0);if(key==='right')move(1,0);if((key==='a'||key==='start')&&(state==='title'||state==='over'))start();else if(key==='start'&&state!=='title'&&state!=='over')pause();if(key==='select'||(key==='b'&&state!=='play'))services.exit()},unmount(){clearTimeout(timer)}};
}};
