import { createGameContext, safeDelta, smoothToward } from '../../js/render-utils.js?v=2.2.0';

const WIDTH=320,HEIGHT=240,GROUND=205,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export default{
  id:'pocket-fighter',title:'Pocket Fighter',version:'1.0.0',
  create(){
    let root,canvas,ctx,services,frame=0,previousTime=0,state='title',player,cpu,round=1,roundTimer=0,wins=0;
    let held={left:false,right:false,down:false},particles=[],message='',lastPlayerAttack=0;
    const markup=()=>`<div class="fighter-game"><canvas width="640" height="480" aria-label="Pocket Fighter arena"></canvas><div class="fighter-hud"><span>KSR <b id="fighter-player-rounds">0</b></span><strong>ROUND <b id="fighter-round">1</b></strong><span>VEX <b id="fighter-cpu-rounds">0</b></span></div><div class="fighter-health"><i id="fighter-player-health"></i><i id="fighter-cpu-health"></i></div><div class="fighter-message" id="fighter-message"></div><div class="fighter-overlay" id="fighter-overlay"><strong>POCKET FIGHTER</strong><small>BEST OF THREE - PRO CPU<br>BLOCK, COUNTER, AND CONTROL SPACE</small><button data-fighter="start">FIGHT</button><em>LEFT / RIGHT - UP JUMP - DOWN BLOCK - A/B ATTACK</em></div><div class="fighter-pause" id="fighter-pause" hidden>PAUSED</div><button class="fighter-exit" data-fighter="exit" aria-label="Exit game">X</button></div>`;
    function makeFighter(x,color,ai=false){return{x,y:GROUND-20,vx:0,vy:0,face:ai?-1:1,hp:100,rounds:0,grounded:true,block:false,attack:null,stun:0,think:.2,color,ai};}
    function resetMatch(){round=1;player=makeFighter(84,'#f4f6f7');cpu=makeFighter(236,'#71899a',true);particles=[];roundTimer=0;message='ROUND 1';held={left:false,right:false,down:false};}
    function resetRound(){const pr=player.rounds,cr=cpu.rounds;player=makeFighter(84,'#f4f6f7');cpu=makeFighter(236,'#71899a',true);player.rounds=pr;cpu.rounds=cr;message=`ROUND ${round}`;roundTimer=0;}
    function updateHud(){if(!root)return;root.querySelector('#fighter-player-rounds').textContent=player?.rounds||0;root.querySelector('#fighter-cpu-rounds').textContent=cpu?.rounds||0;root.querySelector('#fighter-round').textContent=round;root.querySelector('#fighter-player-health').style.width=`${Math.max(0,player?.hp||0)}%`;root.querySelector('#fighter-cpu-health').style.width=`${Math.max(0,cpu?.hp||0)}%`;root.querySelector('#fighter-message').textContent=message;}
    function show(title,copy,button){const o=root.querySelector('#fighter-overlay');o.hidden=false;o.innerHTML=`<strong>${title}</strong><small>${copy}</small><button data-fighter="start">${button}</button><em>LEFT / RIGHT - UP JUMP - DOWN BLOCK - A/B ATTACK</em>`;}
    function renderUi(){root.querySelector('#fighter-pause').hidden=state!=='pause';if(state==='title')show('POCKET FIGHTER',`BEST OF THREE - PRO CPU<br>${wins} CAREER WINS`,'FIGHT');else if(state==='over')show(player.rounds>cpu.rounds?'KSR WINS':'VEX WINS',`${player.rounds} - ${cpu.rounds}<br>${player.rounds>cpu.rounds?'CHAMPIONSHIP SECURED':'CPU COUNTERED YOUR PLAN'}`,'REMATCH');else root.querySelector('#fighter-overlay').hidden=true;updateHud();}
    function start(){resetMatch();state='play';services.tone(360,.08,'square');renderUi();}
    function jump(fighter){if(fighter.grounded&&fighter.stun<=0){fighter.vy=-205;fighter.grounded=false;if(!fighter.ai)services.tone(470,.035,'square');}}
    function attack(fighter,type){if(fighter.stun>0||fighter.attack||fighter.block)return;const special=type==='special';fighter.attack={type,timer:special?.46:type==='kick'?.34:.25,active:special?.25:type==='kick'?.18:.13,range:special?42:type==='kick'?31:23,damage:special?22:type==='kick'?15:10,connected:false};if(!fighter.ai)services.tone(special?185:type==='kick'?240:310,.035,'sawtooth');}
    function burst(x,y,color,count=7){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*90,vy:-15-Math.random()*60,life:.4,color});}
    function hit(attacker,defender,attack){if(attack.connected)return;const distance=Math.abs(attacker.x-defender.x);if(distance>attack.range||Math.abs(attacker.y-defender.y)>28)return;attack.connected=true;let damage=attack.damage;if(defender.block&&defender.grounded){damage=Math.ceil(damage*.22);attacker.stun=.11;services.tone(165,.035,'square');}else{defender.stun=attack.type==='special'?.46:.23;defender.vx=attacker.face*(attack.type==='special'?145:86);defender.vy=attack.type==='special'?-80:-35;services.tone(95,.06,'square');}defender.hp-=damage;burst(defender.x,defender.y-9,defender.block?'#9bdfff':'#fff',defender.block?5:10);if(defender.hp<=0)endRound(attacker);}
    function endRound(winner){if(roundTimer>0)return;winner.rounds+=1;roundTimer=1.3;message=winner===player?'KSR ROUND':'CPU ROUND';services.tone(winner===player?760:130,.12,winner===player?'triangle':'sawtooth');updateHud();}
    function finishMatch(){state='over';if(player.rounds>cpu.rounds){wins+=1;services.storage.set('pocketFighter:wins',wins);}renderUi();}
    function updateAttack(fighter,opponent,dt){if(!fighter.attack)return;fighter.attack.timer-=dt;fighter.attack.active-=dt;if(fighter.attack.active<=0&&!fighter.attack.connected)hit(fighter,opponent,fighter.attack);if(fighter.attack.timer<=0)fighter.attack=null;}
    function cpuBrain(dt){cpu.think-=dt;if(cpu.think>0||cpu.stun>0)return;cpu.think=.075+Math.random()*.085;const dx=player.x-cpu.x,d=Math.abs(dx);cpu.face=Math.sign(dx)||cpu.face;cpu.block=false;if(player.attack&&d<player.attack.range+13&&Math.random()<.72){cpu.block=true;cpu.vx=0;return;}if(d>48){cpu.vx=Math.sign(dx)*(61+round*3);if(player.grounded&&d>105&&Math.random()<.05)jump(cpu);return;}if(d<22&&Math.random()<.38){cpu.vx=-Math.sign(dx)*55;return;}cpu.vx=0;const roll=Math.random();if(roll<.28)attack(cpu,'special');else if(roll<.68)attack(cpu,'kick');else attack(cpu,'punch');}
    function physics(fighter,dt){fighter.stun=Math.max(0,fighter.stun-dt);fighter.vy+=430*dt;fighter.x=clamp(fighter.x+fighter.vx*dt,22,298);fighter.y+=fighter.vy*dt;if(fighter.y>=GROUND-20){fighter.y=GROUND-20;fighter.vy=0;fighter.grounded=true;}fighter.vx=smoothToward(fighter.vx,0,fighter.grounded?9:2,dt);}
    function update(dt){particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=110*dt;p.life-=dt;});particles=particles.filter(p=>p.life>0);if(state!=='play')return;if(roundTimer>0){roundTimer-=dt;if(roundTimer<=0){if(player.rounds>=2||cpu.rounds>=2)finishMatch();else{round+=1;resetRound();}}return;}const move=(held.right?1:0)-(held.left?1:0);if(player.stun<=0&&!player.attack){player.block=held.down&&player.grounded;if(!player.block&&move)player.vx=move*72;}player.face=Math.sign(cpu.x-player.x)||1;cpu.face=-player.face;cpuBrain(dt);updateAttack(player,cpu,dt);updateAttack(cpu,player,dt);physics(player,dt);physics(cpu,dt);if(Math.abs(player.x-cpu.x)<18){const push=(18-Math.abs(player.x-cpu.x))*.5;player.x-=player.face*push;cpu.x+=player.face*push;}updateHud();}
    function drawFighter(fighter){ctx.save();ctx.translate(fighter.x,fighter.y);ctx.scale(fighter.face,1);ctx.fillStyle='#0006';ctx.beginPath();ctx.ellipse(0,20,12,4,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=fighter.color;ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(-3,5);ctx.lineTo(-7,19);ctx.moveTo(3,5);ctx.lineTo(8,19);ctx.stroke();ctx.fillStyle=fighter.block?'#90bed2':fighter.color;ctx.beginPath();ctx.roundRect(-8,-10,16,20,4);ctx.fill();ctx.fillStyle='#11161a';ctx.beginPath();ctx.arc(0,-16,6,0,Math.PI*2);ctx.fill();ctx.strokeStyle=fighter.color;ctx.lineWidth=4;if(fighter.block){ctx.beginPath();ctx.moveTo(5,-5);ctx.lineTo(12,-14);ctx.stroke();}else if(fighter.attack){const reach=fighter.attack.type==='special'?27:fighter.attack.type==='kick'?22:17;ctx.beginPath();ctx.moveTo(5,-4);ctx.lineTo(reach,fighter.attack.type==='kick'?8:-5);ctx.stroke();if(fighter.attack.type==='special'){ctx.strokeStyle='#a8e8ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(19,-3,12,-1.2,1.2);ctx.stroke();}}else{ctx.beginPath();ctx.moveTo(5,-4);ctx.lineTo(11,2);ctx.stroke();}ctx.restore();}
    function draw(){const bg=ctx.createLinearGradient(0,0,0,HEIGHT);bg.addColorStop(0,'#111822');bg.addColorStop(1,'#3f4b55');ctx.fillStyle=bg;ctx.fillRect(0,0,WIDTH,HEIGHT);ctx.fillStyle='#0b0e12';for(let i=0;i<25;i++){const x=i*14,y=55+(i%4)*7;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();ctx.fillRect(x-4,y+3,8,13);}ctx.fillStyle='#20282e';ctx.fillRect(0,92,320,113);ctx.strokeStyle='#71818b';ctx.beginPath();ctx.moveTo(0,122);ctx.lineTo(320,122);ctx.moveTo(160,92);ctx.lineTo(160,205);ctx.stroke();ctx.fillStyle='#080a0c';ctx.fillRect(0,205,320,35);drawFighter(player);drawFighter(cpu);particles.forEach(p=>{ctx.globalAlpha=clamp(p.life*3,0,1);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,2,2);});ctx.globalAlpha=1;}
    function loop(time){const dt=safeDelta(time,previousTime,.034);previousTime=time;update(dt);draw();frame=requestAnimationFrame(loop);}
    return{async mount(host,provided){services=provided;wins=services.storage.get('pocketFighter:wins',0);host.innerHTML=markup();root=host.firstElementChild;canvas=root.querySelector('canvas');ctx=createGameContext(canvas,WIDTH,HEIGHT);resetMatch();state='title';renderUi();previousTime=performance.now();frame=requestAnimationFrame(loop);root.addEventListener('click',event=>{const action=event.target.closest?.('[data-fighter]')?.dataset.fighter;if(action==='start')start();if(action==='exit')services.exit();});canvas.addEventListener('pointerdown',event=>{if(state!=='play')return;const rect=canvas.getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width,y=(event.clientY-rect.top)/rect.height;if(y<.48)jump(player);else if(x<.3)held.left=true;else if(x>.7)held.right=true;else attack(player,'punch');});canvas.addEventListener('pointerup',()=>{held.left=held.right=false;});},input(key,down){if(key==='left')held.left=down;if(key==='right')held.right=down;if(key==='down')held.down=down;if(!down)return;if((key==='a'||key==='start')&&(state==='title'||state==='over'))start();else if(key==='start'){state=state==='pause'?'play':'pause';renderUi();}else if(state==='play'){if(key==='up')jump(player);if(key==='a'){lastPlayerAttack=performance.now();attack(player,'punch');}if(key==='b')attack(player,held.down||performance.now()-lastPlayerAttack<180?'special':'kick');}if(key==='select')services.exit();},setAuthority(){},unmount(){cancelAnimationFrame(frame);}};
  }
};
